# Site
name: Locatify
description: Site for Locatify mobile app for tourists and explorers
meta_description: "Locatify let explore."
logo: 'assets/images/kelvin.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
<<<<<<< HEAD
baseurl: 
=======
baseurl:
>>>>>>> f329bd25ed0deff599462c5ea8112585aa4f7e21
email: '9alile1@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  kelvin:
    name: Kelvin Shoo
    display_name: Kelvin
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 9alile1@gmail.com
    web: https://9alile1.github.io/locatify/
    twitter: https://twitter.com/9alile1
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
